# 有限体の拡大体を生成元から計算する
### これまでの経験から練り直してみる。
先ずは, 環境の確認と, **Pkg**の導入から

In [1]:
println(versioninfo())
using Nemo,Combinatorics,Dates,Primes

Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
nothing

Welcome to Nemo version building

Nemo comes with absolutely no warranty whatsoever


#### 確認していくこと
※ $p,n$を変えたときに既約多項式や生成元を自動で選びたいんだけど...
素数 $p$ に対する有限体 $GF(p)$ を剰余系の計算のみで構成する。  
これは簡単で,  $0,\cdots, p-1$ の配列なり集合で良い。  
次に, $n$ を $2$ 以上の整数とし, $GF(p^n)$ を同様に構成したい。  
既約多項式を見つけて, そのうち, 根が生成元(原始元)となるものを確認し, 構成すれば良い。  
ただし, **Nemo** は用いずに... だ。  
### **Nemo** を用いた場合を確認しておく。

In [85]:
#function makeGFwithNemo(p)# 位数 p な Galoir Field を作る。要らんやろこれ。
#    GF(p)
#end
#function makeSetelementList(G)# これも collect で良さげ。
#    Gl=[]
#    for e ∈ G
#        push!(Gl,e)
#    end
#    Gl
#end
all_perm(x, n) = vec(map(collect, Iterators.product(ntuple(_ -> x, n)...)))# 配列 x の要素を n 個並べた「重複順列」の配列を作る
#
p,n=3,2# 具体例の為の p,n の設定
p,n=3,4# 具体例の為の p,n の設定
p,n=3,5# 具体例の為の p,n の設定
#GFp=GF(p)#makeGFwithNemo(p)$ GF(p)を拵えて, GFp とする # Nemo.jl を利用するなら
GFp=Vector(0:p-1)# 整数で処理するならこれで
#GFpl=makeGFelementList(GFp)
#GFpl=collect(GFp)# Nemo を利用した場合は, GFp は配列ではないので, 配列にしたものを GFpl としておく
#println(GFpl)# Nemo を利用した場合に
println(join(GFp,","))# GFp の元を配列な　GFpl で表示する。
#GFpx,x = GFp["x"]
IrreduciblePolynomialList=[]# 既約多項式の係数配列を入れる配列
coeflst=all_perm(GFp, n)# 重複順列を利用して, GFpを係数とする n 次多項式の n-1 次以下の係数候補を配列で拵える。
#                         n次の係数は 1 だからそこは拵えずに処理を進めている。
for j=1:length(coeflst)
    prnstrl=[]
    chk=true
    for x=0:p-1
        prnstr=string(x)*"^"*string(n)
        val=x^n
        for i=1:n
            val=(val+coeflst[j][i]*x^(n-i))%p
            val=val
            if coeflst[j][i]!=0
                prnstr=prnstr*"+"*string(coeflst[j][i])*"×"*string(x)*"^"*string(n-i)
            end
        end
        if val!=0
            push!(prnstrl,"f("*string(x)*")="*prnstr*"≡"*string(val))
        else
            chk=false
            break
        end
    end
    if chk
        push!(IrreduciblePolynomialList,coeflst[j])
        println(coeflst[j])
        println(join(prnstrl,", "))
    end
end
#println(join(IrreduciblePolynomialList,", "))
prnstrl=[]
for cl ∈ IrreduciblePolynomialList
    push!(prnstrl,"("*join(cl,",")*")")
end
println(join(prnstrl,", "))

0,1,2
[2, 0, 0, 0, 1]
f(0)=0^5+2×0^4+1×0^0≡1, f(1)=1^5+2×1^4+1×1^0≡1, f(2)=2^5+2×2^4+1×2^0≡2
[2, 1, 0, 0, 1]
f(0)=0^5+2×0^4+1×0^3+1×0^0≡1, f(1)=1^5+2×1^4+1×1^3+1×1^0≡2, f(2)=2^5+2×2^4+1×2^3+1×2^0≡1
[0, 2, 0, 0, 1]
f(0)=0^5+2×0^3+1×0^0≡1, f(1)=1^5+2×1^3+1×1^0≡1, f(2)=2^5+2×2^3+1×2^0≡1
[1, 2, 0, 0, 1]
f(0)=0^5+1×0^4+2×0^3+1×0^0≡1, f(1)=1^5+1×1^4+2×1^3+1×1^0≡2, f(2)=2^5+1×2^4+2×2^3+1×2^0≡2
[1, 0, 1, 0, 1]
f(0)=0^5+1×0^4+1×0^2+1×0^0≡1, f(1)=1^5+1×1^4+1×1^2+1×1^0≡1, f(2)=2^5+1×2^4+1×2^2+1×2^0≡2
[1, 1, 1, 0, 1]
f(0)=0^5+1×0^4+1×0^3+1×0^2+1×0^0≡1, f(1)=1^5+1×1^4+1×1^3+1×1^2+1×1^0≡2, f(2)=2^5+1×2^4+1×2^3+1×2^2+1×2^0≡1
[0, 2, 1, 0, 1]
f(0)=0^5+2×0^3+1×0^2+1×0^0≡1, f(1)=1^5+2×1^3+1×1^2+1×1^0≡2, f(2)=2^5+2×2^3+1×2^2+1×2^0≡2
[2, 2, 1, 0, 1]
f(0)=0^5+2×0^4+2×0^3+1×0^2+1×0^0≡1, f(1)=1^5+2×1^4+2×1^3+1×1^2+1×1^0≡1, f(2)=2^5+2×2^4+2×2^3+1×2^2+1×2^0≡1
[0, 0, 2, 0, 1]
f(0)=0^5+2×0^2+1×0^0≡1, f(1)=1^5+2×1^2+1×1^0≡1, f(2)=2^5+2×2^2+1×2^0≡2
[0, 1, 2, 0, 1]
f(0)=0^5+1×0^3+2×0^2+1×0^0≡1, f(1)=1^5+1×1^3+2×1^2+

#### 上の既約多項式候補をリストアップする部分をルーチン化しておこう。

In [86]:
function IrreduciblePolynomialListMaker(p,n)# GF(p)をGF(p^n)に拡大する際に利用する既約多項式をリストアップする
    GFp=Vector(0:p-1)# 整数で処理するための, GF(p) は整数の配列で設定
    coeflst=all_perm(GFp, n)# 重複順列を利用して, GFpを係数とする n 次多項式の n-1 次以下の係数候補を配列で拵える。
#                             n次の係数は 1 だからそこは拵えずに処理を進めている。
    ansl=[]
    for j=1:length(coeflst)
#        prnstrl=[]
        chk=true
        for x=0:p-1
#            prnstr=string(x)*"^"*string(n)
            val=x^n
            for i=1:n
                val=(val+coeflst[j][i]*x^(n-i))%p
#                val=val
#                if coeflst[j][i]!=0
#                    prnstr=prnstr*"+"*string(coeflst[j][i])*"×"*string(x)*"^"*string(n-i)
#                end
            end
            if val!=0
#                push!(prnstrl,"f("*string(x)*")="*prnstr*"≡"*string(val))
            else
                chk=false
                break
            end
        end
        if chk
            push!(ansl,coeflst[j])
#            println(coeflst[j])
#            println(join(prnstrl,", "))
        end
    end
    ansl
end
IPlst=IrreduciblePolynomialListMaker(p,n)
println(IPlst)

Any[[2, 0, 0, 0, 1], [2, 1, 0, 0, 1], [0, 2, 0, 0, 1], [1, 2, 0, 0, 1], [1, 0, 1, 0, 1], [1, 1, 1, 0, 1], [0, 2, 1, 0, 1], [2, 2, 1, 0, 1], [0, 0, 2, 0, 1], [0, 1, 2, 0, 1], [1, 2, 2, 0, 1], [2, 2, 2, 0, 1], [2, 0, 0, 1, 1], [0, 1, 0, 1, 1], [1, 1, 0, 1, 1], [2, 2, 0, 1, 1], [1, 0, 1, 1, 1], [0, 1, 1, 1, 1], [2, 1, 1, 1, 1], [1, 2, 1, 1, 1], [0, 0, 2, 1, 1], [1, 1, 2, 1, 1], [2, 1, 2, 1, 1], [0, 2, 2, 1, 1], [0, 0, 0, 2, 1], [1, 0, 0, 2, 1], [2, 1, 0, 2, 1], [2, 2, 0, 2, 1], [0, 0, 1, 2, 1], [2, 0, 1, 2, 1], [1, 1, 1, 2, 1], [1, 2, 1, 2, 1], [1, 0, 2, 2, 1], [2, 0, 2, 2, 1], [0, 1, 2, 2, 1], [0, 2, 2, 2, 1], [1, 0, 0, 0, 2], [1, 1, 0, 0, 2], [0, 2, 0, 0, 2], [2, 2, 0, 0, 2], [0, 0, 1, 0, 2], [0, 1, 1, 0, 2], [1, 2, 1, 0, 2], [2, 2, 1, 0, 2], [2, 0, 2, 0, 2], [2, 1, 2, 0, 2], [0, 2, 2, 0, 2], [1, 2, 2, 0, 2], [1, 0, 0, 1, 2], [0, 1, 0, 1, 2], [2, 1, 0, 1, 2], [1, 2, 0, 1, 2], [0, 0, 1, 1, 2], [1, 1, 1, 1, 2], [2, 1, 1, 1, 2], [0, 2, 1, 1, 2], [2, 0, 2, 1, 2], [0, 1, 2, 1, 2], [1, 1, 2, 

#### 次にこれらの既約多項式の中から, 生成多項式として利用できるもの, つまり, 根の累乗が GF(p^n) を構成するものをリストアップする。

In [87]:
function PrimitivePolynomialListMaker(p,n)
    IPlst=IrreduciblePolynomialListMaker(p,n)
    ansl=[]
    for cl ∈ IPlst
#    println(" ---------- ")
        Alp=zeros(Int64,n, n)
        for i=2:n
            Alp[i-1,i]=1
        end
        for i=1:n
            Alp[i,1]=(p-cl[i])%p
        end
        be=Vector(1:n).*0
        be[n]=1
        e=be
#    println(e)
    chk=true
        for i=1:p^n-2
            e=(Alp*e).%p
#        println(e)
            if e==be
                chk=false
                break
            end
        end
        if chk
            push!(ansl,cl)
#            println(cl)
#        display(Alp)
#        println("*** OK ***")
        end
    end
    ansl
end
PPlst=PrimitivePolynomialListMaker(p,n)
println(PPlst)

Any[[2, 0, 0, 0, 1], [1, 2, 0, 0, 1], [1, 0, 1, 0, 1], [0, 2, 1, 0, 1], [2, 2, 1, 0, 1], [0, 1, 2, 0, 1], [1, 2, 2, 0, 1], [2, 0, 0, 1, 1], [0, 1, 0, 1, 1], [1, 1, 0, 1, 1], [1, 0, 1, 1, 1], [2, 1, 1, 1, 1], [1, 2, 1, 1, 1], [0, 0, 2, 1, 1], [1, 1, 2, 1, 1], [0, 2, 2, 1, 1], [0, 0, 0, 2, 1], [1, 0, 0, 2, 1], [2, 2, 0, 2, 1], [1, 1, 1, 2, 1], [2, 0, 2, 2, 1], [0, 1, 2, 2, 1]]


漸化式で計算した元と「有限体の拡大」で計算した元がピッタリ一致した。  
が既約多項式の確認や原始元のチェックはしていない。  
そこを実装しよう。  
先ずは, 既約多項式の列挙から。  
想定される多項式に代入チェックを掛ける。

こうして得られた, 原始元(生成元？)を根とする既約多項式(原始多項式？生成多項式？)から一つ選んで, 拡大体を構成すれば良い。  
$GF(p^n)$の構成元(配列表示)を確認してみよう。

In [88]:
function makeGFpnElementList(p,cl)# GF(p) を 係数配列 cl な原始多項式(但し, 最高次な n 次の係数 1 は配列外) で作成した 
#                                   拡大体 GF(p^n) の元を, 配列の配列で列挙する。
#                                   n は原始多項式 cl の係数配列の「大きさ/長さ」になっているので指定は不要な点に注意
    n=length(cl)
    Alp=zeros(Int64,n, n)
    for i=2:n
        Alp[i-1,i]=1
    end
    for i=1:n
        Alp[i,1]=(p-cl[i])%p
    end
    be=Vector(1:n).*0
    ansl=[Vector(1:n).*0]
    be[n]=1
    e=be
    push!(ansl,e)
#    println(e)
    chk=true
    for i=1:p^n-2
        e=(Alp*e).%p
#        println(e)
        if e==be
            chk=false
            println(" *** Break ***")
            break
        else
            push!(ansl,e)
        end
    end
    if !chk
        ansl=[]
    end
    ansl
end
elst=makeGFpnElementList(p,PPlst[2])
println(elst)
println(length(elst),",",length(unique(elst)))

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [2, 1, 0, 0, 2], [2, 2, 0, 2, 1], [0, 2, 2, 1, 1], [2, 2, 1, 1, 0], [0, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 0], [2, 2, 0, 0, 2], [0, 2, 0, 2, 1], [2, 0, 2, 1, 0], [1, 1, 1, 0, 1], [0, 2, 0, 1, 2], [2, 0, 1, 2, 0], [1, 0, 2, 0, 1], [2, 0, 0, 1, 2], [1, 2, 1, 2, 1], [1, 2, 2, 1, 2], [1, 0, 1, 2, 2], [2, 2, 2, 2, 2], [0, 1, 2, 2, 1], [1, 2, 2, 1, 0], [1, 0, 1, 0, 2], [2, 2, 0, 2, 2], [0, 2, 2, 2, 1], [2, 2, 2, 1, 0], [0, 1, 1, 0, 1], [1, 1, 0, 1, 0], [0, 1, 1, 0, 2], [1, 1, 0, 2, 0], [0, 1, 2, 0, 2], [1, 2, 0, 2, 0], [1, 1, 2, 0, 2], [0, 0, 0, 2, 2], [0, 0, 2, 2, 0], [0, 2, 2, 0, 0], [2, 2, 0, 0, 0], [0, 2, 0, 0, 1], [2, 0, 0, 1, 0], [1, 2, 1, 0, 1], [1, 2, 0, 1, 2], [1, 1, 1, 2, 2], [0, 2, 2, 2, 2], [2, 2, 2, 2, 0], [0, 1, 2, 0, 1], [1, 2, 0, 1, 0], [1, 1, 1, 0, 2], [0, 2, 0, 2, 2], [2, 0, 2, 2, 0], [1, 1, 2, 0, 1], [0, 0, 0, 1, 2], [0, 0, 1, 2, 0], [0, 1, 2, 0, 0], [1, 2, 0, 0, 

#### あとの計算の為に, 拡大で利用した原始多項式の根　$\alpha$ の累乗な $\alpha^i$ を返してくれる関数を拵えておこう。

In [89]:
function GFpnElement(p,cl,i)# 原始多項式の原始根 α の累乗 α^i を配列で返してくれる。
    n=length(cl)
    be=Vector(1:n).*0
    be[n]=1
    if i==0
        be
    else
        Alp=zeros(Int64,n, n)
        for i=2:n
            Alp[i-1,i]=1
        end
        for i=1:n
            Alp[i,1]=(p-cl[i])%p
        end
        e=be
        for i=1:i
            e=(Alp*e).%p
        end
        e
    end
end
prnlst=[]
for i=0:10
push!(prnlst,GFpnElement(p,PPlst[2],i))
end
println(join(prnlst,","))

[0, 0, 0, 0, 1],[0, 0, 0, 1, 0],[0, 0, 1, 0, 0],[0, 1, 0, 0, 0],[1, 0, 0, 0, 0],[2, 1, 0, 0, 2],[2, 2, 0, 2, 1],[0, 2, 2, 1, 1],[2, 2, 1, 1, 0],[0, 0, 1, 0, 1],[0, 1, 0, 1, 0]


### 次は更にこれを3次拡大してみる。  
問題はこれが **Nemo** 抜きの剰余系のみの数値計算でいけるかだ。  
同様の段取りで進めるとすれば, 先ずは既約多項式の確認からだ。  
#### 計算が配列になるので相応な準備が必要になる。

#### kα^r×lα^s を処理して配列で返すものを拵えよう
その為には, $GF(p)$ を $GF(p^n)$ に拡大するときに, 既約多項式は何を使っているかも引数に入れておく事にしよう。

In [90]:
ppnum=2# 原始多項式 PrimitivePolynomial の番号
function gfpCalcMulB(p,n,k,r,l,s,cl)# GF(p^n) で, kα^r × lα^s を計算して配列で返す
# 結果は当然, k×l×α^{r+s} となるわけだ。これを a α^b としよう
    a=(k*l)%(p)
    b=(r+s)# ここを最初勘違いして p にしてもうてた
    c=GFpnElement(p,cl,b)
    (a*c).%p
end
println(gfpCalcMulB(p,n,2,3,4,2,PPlst[ppnum]))
println(gfpCalcMulB(p,n,1,0,1,0,PPlst[ppnum]))
println(gfpCalcMulB(p,n,1,1,1,0,PPlst[ppnum]))
println(gfpCalcMulB(p,n,1,1,1,1,PPlst[ppnum]))
println(gfpCalcMulB(p,n,1,1,1,2,PPlst[ppnum]))
println(gfpCalcMulB(p,n,1,1,1,3,PPlst[ppnum]))

[1, 2, 0, 0, 1]
[0, 0, 0, 0, 1]
[0, 0, 0, 1, 0]
[0, 0, 1, 0, 0]
[0, 1, 0, 0, 0]
[1, 0, 0, 0, 0]


#### p=3,n=4 で [2,1,1,2] の2乗の場合はどう計算すれば良いだろう。
これも先ずは汎用に, [a,b,c,...,d]と[e,f,g,...,h]の場合の計算を仕込むべきか。

In [91]:
function gfpCalcMulA(p,n,abcd,efgh,irrpolc)# GF(p^n) で, [a,b,c,...,d] × [e,f,g,...,h] を計算して配列で返す
#                                            つまり, (aα^n-1+bα^n-2+cα^n-3+...+d)(eα^n-1+fα^n-2+gα^n-3+...+h) を計算して係数配列で返す
    ansl=Vector(1:n).*0
    for i=1:n,j=1:n
        ansl=(ansl+gfpCalcMulB(p,n,abcd[i],n-i,efgh[j],n-j,irrpolc)).%p
    end
    ansl
end

gfpCalcMulA (generic function with 1 method)

#### 以下は p=3,n=4 の場合のチェック用

In [92]:
p,n=3,4# 具体例の為の p,n の設定
println("p=",p,", n=",n," で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える")
GFp=Vector(0:p-1)# 整数で処理するならこれで
#println(join(GFp,","))# GFp の元を配列な　GFpl で表示する。
PPlst=PrimitivePolynomialListMaker(p,n)
ppnum=2
println(" ------------------------")
println("選んだ原始多項式は, ",PPlst[ppnum])
println(" ------------------------")
println(gfpCalcMulA(p,n,[1,2,1,2],[2,1,2,1],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[1,2,1,2],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[1,2,1,2],[0,0,0,1],PPlst[ppnum]))
println(" ------------------------")
println(gfpCalcMulA(p,n,[0,0,0,1],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[0,0,1,0],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[0,1,0,0],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[1,0,0,0],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[1,1,0,0],[1,0,0,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[0,0,1,0],[0,0,1,0],PPlst[ppnum]))
println(gfpCalcMulA(p,n,[0,0,1,1],[0,0,1,0],PPlst[ppnum]))
println(" ------------------------")
println(" Nemo で確認してみよう。")
NGFp=GF(p)
NGFpx,x = NGFp["x"]
NGFpnx,α=finite_field(x^4+2x^3+2, "α")
println((α^3+2α^2+α+2)*(2α^3+α^2+2α+1))
println((α^3+2α^2+α+2)*(α))
println((α^3+2α^2+α+2)*(1))
println(" ------------------------")
println((1)*(α))
println((α)*(α))
println((α^2)*(α))
println(α^2*α^2)
println((α)*(α))
println((α+1)*(α))
println(" --- 「配列での原始多項式の行列と配列による累乗の計算による元」と「Nemoでの原始多項式による拡大体での根 α の累乗 α^i による元」とが一致するかの確認 ---")
lst=[]
for i=0:p^n-1
push!(lst,GFpnElement(p,PPlst[ppnum],i))
end
for i=1:length(lst)
    println(i-1,": [",join(lst[i],","),"] : ",α^(i-1))
end
println(" --- ちゃんと一致するようで安心だ ---")


p=3, n=4 で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える
 ------------------------
選んだ原始多項式は, [2, 0, 0, 2]
 ------------------------
[2, 2, 0, 0]
[0, 1, 2, 1]
[1, 2, 1, 2]
 ------------------------
[0, 0, 1, 0]
[0, 1, 0, 0]
[1, 0, 0, 0]
[1, 0, 0, 1]
[2, 1, 2, 2]
[0, 1, 0, 0]
[0, 1, 1, 0]
 ------------------------
 Nemo で確認してみよう。
2*α^3 + 2*α^2
α^2 + 2*α + 1
α^3 + 2*α^2 + α + 2
 ------------------------
α
α^2
α^3
α^3 + 1
α^2
α^2 + α
 --- 「配列での原始多項式の行列と配列による累乗の計算による元」と「Nemoでの原始多項式による拡大体での根 α の累乗 α^i による元」とが一致するかの確認 ---
0: [0,0,0,1] : 1
1: [0,0,1,0] : α
2: [0,1,0,0] : α^2
3: [1,0,0,0] : α^3
4: [1,0,0,1] : α^3 + 1
5: [1,0,1,1] : α^3 + α + 1
6: [1,1,1,1] : α^3 + α^2 + α + 1
7: [2,1,1,1] : 2*α^3 + α^2 + α + 1
8: [0,1,1,2] : α^2 + α + 2
9: [1,1,2,0] : α^3 + α^2 + 2*α
10: [2,2,0,1] : 2*α^3 + 2*α^2 + 1
11: [1,0,1,2] : α^3 + α + 2
12: [1,1,2,1] : α^3 + α^2 + 2*α + 1
13: [2,2,1,1] : 2*α^3 + 2*α^2 + α + 1
14: [1,1,1,2] : α^3 + α^2 + α + 2
15: [2,1,2,1] : 2*α^3 + α^2 + 2*α + 1
16: [0,2,1,2] : 2*α^2 + α + 2


#### 何とか計算できるようになったかも

これで3乗や2乗は簡単にできそう。  
その前にほんまに計算できてるかチェックもか。

In [93]:
function gfpCalcMulN(p,n,abcd,m,irrpolc)# GF(p^n) で abcd で与えられた元の n 乗を計算する。
    if m==0
        ans=Vector(1:n).*0
        ans[n]=1
    elseif m==1
        ans=abcd
    else
        efgh=gfpCalcMulN(p,n,abcd,m-1,irrpolc)
        ans=gfpCalcMulA(p,n,abcd,efgh,irrpolc)
    end
    ans
end
if p==3 && n==4# 以下は p=3,n=4 の場合の計算チェック
    for i=0:6
        println(gfpCalcMulN(p,n,[1,2,1,2],i,PPlst[ppnum]),", ",(α^3+2α^2+α+2)^i)
    end
end

[0, 0, 0, 1], 1
[1, 2, 1, 2], α^3 + 2*α^2 + α + 2
[1, 1, 0, 0], α^3 + α^2
[1, 0, 1, 1], α^3 + α + 1
[1, 1, 0, 1], α^3 + α^2 + 1
[2, 2, 2, 0], 2*α^3 + 2*α^2 + 2*α
[2, 2, 0, 1], 2*α^3 + 2*α^2 + 1


In [94]:
# 3次拡大だから, 今度は既約多項式の次数は3次と決まっている。係数は$Fpn$の元が候補となるので沢山あるはずだ。
#for a ∈ eansl[1],b ∈ eansl[1],c ∈ eansl[1]
#    println([a,b,c]) # a,b,c は x^3+ax^2+bx+c の係数でその候補を虱潰しに調べる。
#    つまり, この方程式に GF(p^n)の元である eansl[1] の要素を一つ一つ代入するわけだ。
#    n=4 なら GF(p^n) の元は αの n-1=3次式 になるが, この係数の配列なので, 大きさ 4 の配列という事になる。
#    既約多項式候補の係数 a,b,c も同様に, 大きさ 4 の配列で扱う事になる。
#    for x ∈ eansl[1]
#    例えば, p=5, n=4 のときで, xの係数の配列が[2,1,3,4]の場合, x^3はどうなるだろう。
#    x=2α^3+α^2+3α+4 だから, x^3=(2α^3+α^2+3α+4)^2 なのだけど... 既約(生成？原始？)多項式により, α^4 以上は α^3 以下に置き換えられる。
#    この程度でも手で計算するのは厄介だから, アルゴリズム化というかプログラム的に処理したい。
#    なるべく汎用性のありそうな手は...
#    先ず, kα^m×lα^n を処理して配列で返すものからか。
#    end
#end

### 次は更に同様の配列と行列による計算でこれを3次拡大してみたい。  
#### 道具は揃ったのではないかと思う。
先ずは既約多項式の選定からだ。

In [12]:
p,n=3,3# 具体例の為の p,n の設定
println("p=",p,", n=",n," で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える")
GFp=Vector(0:p-1)# 整数で処理するならこれで
#println(join(GFp,","))# GFp の元を配列な　GFpl で表示する。
PPlst=PrimitivePolynomialListMaker(p,n)# GF(p)の n 次の原始多項式の一覧を
println(PPlst)
ppnum=2
GFpn=makeGFpnElementList(p,PPlst[ppnum])
println(length(GFpn))
coeflst=all_perm(GFpn, 3)
println("候補となるGF(p^n)係数の3次式の候補の数は, ",length(coeflst),"個")
IP3lst=[]
zerol=Vector(0:p-1).*0
for cl ∈ coeflst
#    println(cl)
    chk=true
    for xl ∈ GFpn
        vall=gfpCalcMulN(p,n,xl,3,PPlst[ppnum])
        for i=1:3
            vall=vall+gfpCalcMulA(p,n,cl[i],gfpCalcMulN(p,n,xl,3-i,PPlst[ppnum]),PPlst[ppnum])
        end
#        println(vall)
        if vall==zerol
#            println(" *** BREAK ***")
            chk=false
            break
        end
    end
    if chk
#        println(cl)
        push!(IP3lst,cl)
    end
end
length(IP3lst)# IP3lst には既約多項式の係数リストが...
println("既約多項式の係数配列の列挙の最後は, ",IP3lst[end])

p=3, n=3 で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える
Any[[2, 0, 1], [2, 1, 1], [0, 2, 1], [1, 2, 1]]
27
候補となるGF(p^n)係数の3次式の候補の数は, 19683個
既約多項式の係数配列の列挙の最後は, [[2, 1, 2], [2, 1, 2], [2, 1, 2]]


#### 一寸これでは数が多すぎる...ここは乱数で係数セットを選んで, 既約多項式で更に原始多項式になるものを選ぶ作戦が順当か。

In [104]:
function IrreduciblePolynomial3checker(p,n,GFpn,cll,irrpolc)# 3次の既約多項式かどうかチェック... あまま
    ans=true
    zerol=Vector(0:p-1).*0
    for xl ∈ GFpn
        vall=gfpCalcMulN(p,n,xl,3,irrpolc)
        for i=1:3
            vall=vall+gfpCalcMulA(p,n,cll[i],gfpCalcMulN(p,n,xl,3-i,irrpolc),irrpolc)
        end
        if vall==zerol
            ans=false
            break
        end
    end
    ans
end
# ------------------------------------------------------------
p,n=3,4# 具体例の為の p,n の設定
println("p=",p,", n=",n," で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える")
GFp=Vector(0:p-1)# 整数で処理するならこれで
#println(join(GFp,","))# GFp の元を配列な　GFpl で表示する。
PPlst=PrimitivePolynomialListMaker(p,n)# GF(p)の n 次の原始多項式の一覧を
println(PPlst)
ppnum=1
GFpn=makeGFpnElementList(p,PPlst[ppnum])

p=3, n=4 で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える
Any[[1, 0, 0, 2], [2, 0, 0, 2], [0, 0, 1, 2], [2, 1, 1, 2], [2, 2, 1, 2], [0, 0, 2, 2], [1, 1, 2, 2], [1, 2, 2, 2]]


81-element Vector{Vector{Int64}}:
 [0, 0, 0, 0]
 [0, 0, 0, 1]
 [0, 0, 1, 0]
 [0, 1, 0, 0]
 [1, 0, 0, 0]
 [2, 0, 0, 1]
 [1, 0, 1, 2]
 [2, 1, 2, 1]
 [2, 2, 1, 2]
 [0, 1, 2, 2]
 [1, 2, 2, 0]
 [1, 2, 0, 1]
 [1, 0, 1, 1]
 ⋮
 [0, 0, 1, 2]
 [0, 1, 2, 0]
 [1, 2, 0, 0]
 [1, 0, 0, 1]
 [2, 0, 1, 1]
 [1, 1, 1, 2]
 [0, 1, 2, 1]
 [1, 2, 1, 0]
 [1, 1, 0, 1]
 [0, 0, 1, 1]
 [0, 1, 1, 0]
 [1, 1, 0, 0]

#### 取り敢えず既約多項式チェックはできた感じ。次は, ... 根の累乗計算と, それが3次の拡大体を構成するかチェック。
計算の為に, 行列を仕込むのだけど, 行列の成分が配列になるようにできるだろうか？

In [105]:
println("p=",p,", n=",n," で有限体 GF(p) からGF(p^n)を拵えて3次拡大")
e=Vector(1:n).*0
pv=(Vector(1:n).*0).+p
#e[n]=1
Alps=[e,e,e]
#display(Alps)
Alpp=[Alps Alps Alps]
println("Alpp = ")
display(Alpp)
println("--")
ee=copy(e)
ee[n]=1
for i=2:3
    Alpp[i-1,i]=ee
end
#Alpp[1,2]=ee
for i=1:3
    Alpp[i,1]=pv-cll[i]
end
println("Alpp = ")
display(Alpp)

p=3, n=4 で有限体 GF(p) からGF(p^n)を拵えて3次拡大
Alpp = 


3×3 Matrix{Vector{Int64}}:
 [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]
 [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]
 [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

--
Alpp = 


3×3 Matrix{Vector{Int64}}:
 [2, 3, 2, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [3, 3, 3, 3]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [3, 2, 3, 3]  [0, 0, 0, 0]  [0, 0, 0, 0]

#### この行列を拵えるルーチンを拵えないとね。

#### 適当に $GF(p^n)$ の元から3つ選んでそれを係数とする 3次多項式（但し, 3次の係数は 1 固定）を用意する。
既約多項式かどうかはチェックする。

In [106]:
GFpnlen=length(GFpn)
cll=[GFpn[rand(1:GFpnlen)],GFpn[rand(1:GFpnlen)],GFpn[rand(1:GFpnlen)]]
if IrreduciblePolynomial3checker(p,n,GFpn,cll,PPlst[ppnum])
    println("乱数で係数を決めてOKが出た既約多項式 cll = ",cll)
end

乱数で係数を決めてOKが出た既約多項式 cll = [[1, 1, 2, 1], [0, 2, 2, 2], [1, 0, 0, 1]]


#### こうして得られた $GF(p^n)$の元（配列）を係数とする 3次多項式（但し, 3次の係数は 1 固定）から行列を...

In [107]:
function gfpMake3Matrix(p,n,cll)# GF(p^n) n次配列係数の3次の多項式 cll から, ωの累乗用の 3×3行列を用意する
    e=Vector(1:n).*0# n次の 0配列を用意する
    pv=(Vector(1:n).*0).+p# n次の要素が全て p の配列を用意する
    Alps=[e,e,e]# 3×3行列の「列」を用意する。
    Alpp=[Alps Alps Alps]# それを3つ並べて 3×3の 0行列を用意する。
    ee=copy(e)# 最初に用意した 0配列をコピーする
    ee[n]=1# 第 n 成分のみを 1 にする。
    for i=2:3
        Alpp[i-1,i]=ee
    end
    for i=1:3
        Alpp[i,1]=(pv-cll[i]).%p
    end
    Alpp
end
Alpp=gfpMake3Matrix(p,n,cll)
display(Alpp)

3×3 Matrix{Vector{Int64}}:
 [2, 2, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 1, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

何とかできたのだろうか？  
次はこれで $\omega$ の累乗を計算するのだけど...

In [108]:
function gfpCalcMatVec(p,n,A,V,irrpolc)# 配列要素の3×3行列に配列要素のベクトルを掛ける計算
#    display(A)
#    display(V)
    ansl=[Vector(1:n).*0]
    ansA=[ansl ansl ansl]
#    println("ansl=",ansA)
    for i=1:3
#        println(p,",",n,",",A[i],",",V[i],",",irrpolc)
        ansA[i]=(gfpCalcMulA(p,n,A[i],V[1],irrpolc)+gfpCalcMulA(p,n,A[i+3],V[2],irrpolc)+gfpCalcMulA(p,n,A[i+6],V[3],irrpolc)).%p
#        println(i," > ",ansA[i])
    end
#    println(ansA)
    ansA
end
coefl=[Vector(1:n).*0]
display(coefl)
coeflo=copy(coefl)
coeflo[1][n]=1
coefl=[Vector(1:n).*0]
display(coeflo)
display(coefl)
coefA=[coefl coefl coeflo]
display(coefA)
be=[coefl coefl coeflo]
e=be
display(e)
println(" >>> ")
es=Vector(1:n).*0
et=copy(es)
et[n]=1
println(es,", ",et)
println("Irr = ",PPlst[ppnum])
display(Alpp)
for g=1:(p^n)^3+1
    e=gfpCalcMatVec(p,n,Alpp,e,PPlst[ppnum])
#    println(g," : ",e)
    if (e[1]==es) && (e[2]==es) && (e[3]==et)
#        println(g," : ",e)
        if g==(p^n)^3-1
            println("*** OK ***")
        else
            println(" *** ",g," *** Failed ***")            
        end
        break
    end
end
println(" *** fin. ***")
println((p^n)^3)

1-element Vector{Vector{Int64}}:
 [0, 0, 0, 0]

1-element Vector{Vector{Int64}}:
 [0, 0, 0, 1]

1-element Vector{Vector{Int64}}:
 [0, 0, 0, 0]

1×3 Matrix{Vector{Int64}}:
 [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]

1×3 Matrix{Vector{Int64}}:
 [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]

 >>> 
[0, 0, 0, 0], [0, 0, 0, 1]
Irr = [1, 0, 0, 2]


3×3 Matrix{Vector{Int64}}:
 [2, 2, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 1, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

 *** 3280 *** Failed ***
 *** fin. ***
531441


#### 何とか計算できたようだ。

In [109]:
function PrimitivePolynomial3Picker(p,n,GFpn,irrpolc)# 3次の原始多項式をピックアップ。乱数頼りで
    GFpnlen=length(GFpn)
    chkA=false
    cll=[]
    while chkA==false
        cll=[GFpn[rand(1:GFpnlen)],GFpn[rand(1:GFpnlen)],GFpn[rand(1:GFpnlen)]]
        if IrreduciblePolynomial3checker(p,n,GFpn,cll,PPlst[ppnum])
#            display(cll)
            println(cll)
            Alpp=gfpMake3Matrix(p,n,cll)
            display(Alpp)
#        println("乱数で係数を決めてOKが出た既約多項式 cll = ",cll)
            es=Vector(1:n).*0
            eo=copy(es)
            eo[n]=1
            be=[es,es,eo]
            e=be
            println("> ",e)
            for g=1:(p^n)^3+2
                e=gfpCalcMatVec(p,n,Alpp,e,PPlst[ppnum])
                if (g-1)%((p^n)^2)==0
                    println(g-1,"/",(p^n)^3-1," : ",e)
                end
                if (e[1]==es) && (e[2]==es) && (e[3]==eo)
                    println(g," : ",e," ",(p^n)^3-1)
                    if g>=(p^n)^3-1
                        chkA=true
#                        println("*** OK ***")
                    else
                        println("*** ",g," *** Failed ***")            
                    end
                    break
                end
            end
            println(" *** fin. ***")
#            println((p^n)^3)
        end
    end
    cll
end
println("p=",p,", n=",n," で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える")
ansl=PrimitivePolynomial3Picker(p,n,GFpn,PPlst[ppnum])
println(ansl)

p=3, n=4 で有限体 GF(p) から, 原始多項式を一つ選んで, GF(p^n)を拵える
[[1, 0, 1, 2], [2, 2, 0, 0], [1, 1, 0, 0]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 2, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 1, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 2, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[0, 0, 2, 2], [1, 1, 0, 1], [0, 0, 2, 0]]


3×3 Matrix{Vector{Int64}}:
 [0, 0, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 2, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
3280 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 3280 *** Failed ***
 *** fin. ***
[[1, 2, 1, 0], [2, 2, 0, 1], [2, 1, 2, 1]]


3×3 Matrix{Vector{Int64}}:
 [2, 1, 2, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 1, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 2, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[2, 2, 1, 1], [0, 0, 2, 2], [2, 0, 2, 1]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 2, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 0, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
656 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 656 *** Failed ***
 *** fin. ***
[[1, 0, 1, 0], [2, 0, 2, 0], [2, 2, 1, 0]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 2, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 1, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[2, 2, 2, 1], [2, 2, 2, 2], [0, 0, 2, 1]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 1, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 0, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
80 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 80 *** Failed ***
 *** fin. ***
[[1, 0, 1, 2], [1, 0, 0, 0], [2, 0, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 2, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 0, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[1, 0, 0, 2], [1, 0, 0, 0], [0, 0, 2, 0]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 0, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
3280 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 3280 *** Failed ***
 *** fin. ***
[[1, 0, 2, 1], [0, 0, 0, 1], [0, 2, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 1, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[1, 0, 2, 1] [2, 2, 2, 1] [2, 2, 2, 2]]
13122/531440 : [[1, 1, 1, 2] [1, 2, 2, 1] [1, 1, 0, 2]]
19683/531440 : [[0, 2, 2, 0] [1, 1, 1, 0] [1, 2, 0, 0]]
26244/531440 : [[1, 1, 2, 1] [2, 0, 2, 2] [1, 0, 0, 2]]
32805/531440 : [[0, 1, 1, 1] [2, 2, 2, 1] [1, 1, 2, 1]]
39366/531440 : [[0, 1, 1, 0] [0, 2, 0, 2] [2, 1, 0, 2]]
45927/531440 : [[2, 0, 1, 0] [0, 2, 2, 2] [2, 1, 0, 0]]
52488/531440 : [[1, 0, 1, 2] [0, 1, 0, 2] [0, 0, 2, 0]]
59049/531440 : [[1, 1, 0, 1] [0, 0, 0, 0] [0, 2, 1, 2]]
65610/531440 : [[0, 0, 1, 0] [1, 0, 2, 1] [2, 1, 2, 2]]
66430 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 66430 *** Failed ***
 *** fin. ***
[[2, 2, 1, 1], [0, 1, 2, 1], [1, 2, 0, 2]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 2, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 2, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 0, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[1, 2, 1, 1], [0, 1, 1, 0], [0, 2, 0, 0]]


3×3 Matrix{Vector{Int64}}:
 [2, 1, 2, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 2, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 1, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
120 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 120 *** Failed ***
 *** fin. ***
[[2, 2, 2, 2], [0, 2, 1, 1], [1, 2, 1, 0]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 1, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[1, 0, 2, 0], [0, 2, 1, 0], [2, 0, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 1, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 1, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 0, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
3280 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 3280 *** Failed ***
 *** fin. ***
[[0, 1, 0, 1], [1, 2, 2, 1], [2, 1, 1, 2]]


3×3 Matrix{Vector{Int64}}:
 [0, 2, 0, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 1, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 2, 2, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[0, 1, 1, 0], [0, 2, 1, 1], [0, 1, 1, 2]]


3×3 Matrix{Vector{Int64}}:
 [0, 2, 2, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 1, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 2, 2, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
3280 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 3280 *** Failed ***
 *** fin. ***
[[2, 0, 1, 1], [0, 0, 0, 1], [0, 0, 2, 1]]


3×3 Matrix{Vector{Int64}}:
 [1, 0, 2, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 0, 1, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[0, 1, 2, 0] [2, 2, 0, 1] [0, 0, 1, 2]]
13122/531440 : [[1, 1, 0, 2] [2, 1, 0, 1] [0, 1, 1, 0]]
18980 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 18980 *** Failed ***
 *** fin. ***
[[0, 2, 0, 2], [1, 1, 1, 1], [0, 1, 0, 2]]


3×3 Matrix{Vector{Int64}}:
 [0, 1, 0, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 2, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 2, 0, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[1, 0, 2, 1], [0, 1, 0, 0], [1, 2, 2, 2]]


3×3 Matrix{Vector{Int64}}:
 [2, 0, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 2, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[0, 1, 1, 0] [1, 0, 2, 1] [1, 2, 1, 1]]
13122/531440 : [[2, 0, 1, 2] [2, 2, 2, 0] [2, 1, 1, 1]]
19683/531440 : [[0, 2, 0, 2] [2, 1, 1, 2] [1, 0, 0, 1]]
26244/531440 : [[2, 1, 1, 0] [0, 0, 2, 2] [0, 1, 2, 0]]
32805/531440 : [[2, 0, 1, 0] [1, 2, 2, 0] [2, 1, 1, 0]]
39366/531440 : [[2, 0, 2, 0] [2, 2, 0, 1] [2, 1, 0, 2]]
45927/531440 : [[2, 0, 2, 2] [1, 0, 1, 0] [0, 0, 2, 0]]
52488/531440 : [[0, 2, 2, 1] [1, 2, 0, 0] [0, 0, 0, 1]]
59049/531440 : [[2, 1, 1, 0] [1, 1, 1, 0] [1, 1, 0, 1]]
65610/531440 : [[2, 2, 2, 2] [2, 2, 1, 0] [2, 2, 0, 1]]
72171/531440 : [[0, 0, 2, 2] [1, 1, 1, 1] [2, 2, 1, 2]]
78732/531440 : [[0, 0, 2, 1] [1, 0, 0, 2] [0, 0, 1, 1]]
85293/531440 : [[0, 1, 2, 2] [0, 2, 2, 2] [0, 0, 1, 1]]
91854/531440 : [[0, 1, 0, 0] [1, 0, 0, 0] [1, 0, 2, 1]]
98415/531440 : [[2, 0, 2, 2] [2, 1, 2, 2] [0, 2, 2, 0]]
104976/531440 : [[0, 2, 2, 0] [0, 2, 2, 2] [0, 1, 0, 1]]
111537/

3×3 Matrix{Vector{Int64}}:
 [0, 0, 0, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 1, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
3280 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 3280 *** Failed ***
 *** fin. ***
[[2, 1, 0, 2], [2, 2, 1, 0], [1, 2, 2, 0]]


3×3 Matrix{Vector{Int64}}:
 [1, 2, 0, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 1, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[2, 0, 2, 2], [1, 1, 1, 1], [1, 0, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [1, 0, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 2, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[2, 0, 0, 1] [2, 2, 0, 2] [1, 2, 0, 1]]
13122/531440 : [[1, 1, 0, 1] [1, 2, 0, 0] [1, 2, 2, 1]]
19683/531440 : [[1, 2, 0, 2] [1, 0, 2, 1] [2, 1, 1, 1]]
26244/531440 : [[1, 1, 2, 1] [1, 2, 1, 0] [2, 1, 0, 0]]
32805/531440 : [[0, 0, 1, 2] [1, 0, 1, 0] [2, 2, 1, 2]]
39366/531440 : [[0, 2, 2, 0] [1, 1, 1, 2] [2, 1, 1, 1]]
45927/531440 : [[0, 0, 1, 2] [0, 0, 0, 1] [2, 0, 0, 0]]
52488/531440 : [[1, 2, 2, 1] [0, 2, 0, 0] [2, 1, 1, 1]]
59049/531440 : [[1, 1, 0, 0] [1, 1, 1, 2] [0, 1, 0, 1]]
65610/531440 : [[0, 1, 1, 0] [2, 1, 0, 0] [0, 0, 1, 1]]
72171/531440 : [[1, 1, 0, 2] [2, 2, 2, 1] [1, 1, 2, 2]]
78732/531440 : [[1, 1, 0, 1] [1, 0, 2, 2] [0, 1, 0, 0]]
85293/531440 : [[1, 2, 2, 2] [2, 2, 2, 1] [2, 0, 0, 1]]
91854/531440 : [[1, 0, 1, 2] [1, 1, 2, 1] [0, 0, 0, 0]]
98415/531440 : [[0, 2, 1, 1] [1, 0, 1, 2] [0, 2, 1, 1]]
104976/531440 : [[2, 0, 2, 1] [0, 0, 1, 2] [2, 1, 2, 1]]
111537/

#### 何やらできてるのかも
そうすると, ここから巡回平面を考える事になる。

In [110]:
cll=PrimitivePolynomial3Picker(p,n,GFpn,PPlst[ppnum])
Alpp=gfpMake3Matrix(p,n,cll)
display(Alpp)
#        println("乱数で係数を決めてOKが出た既約多項式 cll = ",cll)
es=Vector(1:n).*0
eo=copy(es)
eo[n]=1
be=[es,es,eo]
e=be
println("> ",e)
cdl=[]
for g=1:(p^n)^3+2
    e=gfpCalcMatVec(p,n,Alpp,e,PPlst[ppnum])
    if (e[3]==es)
        println(g,e)
        push!(cdl,g)
    end
end
println(join(cdl,","))
println(length(cdl),", ",(p^n)^2+1)

[[0, 0, 2, 1], [0, 1, 1, 1], [2, 1, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [0, 0, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [0, 2, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 2, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[0, 1, 1, 2] [1, 0, 2, 0] [0, 0, 0, 1]]
13122/531440 : [[2, 0, 1, 0] [2, 0, 1, 0] [1, 2, 1, 0]]
19683/531440 : [[1, 0, 2, 2] [0, 1, 1, 1] [0, 1, 1, 0]]
26244/531440 : [[2, 0, 1, 2] [1, 1, 2, 2] [0, 2, 2, 0]]
32805/531440 : [[2, 1, 0, 1] [1, 2, 2, 0] [2, 2, 2, 0]]
39366/531440 : [[2, 2, 2, 0] [0, 1, 1, 2] [1, 0, 2, 2]]
45927/531440 : [[1, 0, 0, 1] [1, 1, 2, 1] [1, 0, 2, 1]]
52488/531440 : [[1, 2, 2, 0] [0, 0, 0, 2] [1, 2, 2, 1]]
59049/531440 : [[2, 0, 1, 0] [1, 1, 2, 2] [2, 0, 1, 0]]
65610/531440 : [[1, 0, 2, 0] [1, 2, 0, 0] [0, 0, 2, 1]]
72171/531440 : [[0, 1, 2, 0] [2, 0, 2, 2] [0, 0, 2, 0]]
78732/531440 : [[1, 0, 2, 0] [1, 2, 0, 0] [1, 0, 2, 2]]
85293/531440 : [[2, 1, 1, 0] [2, 2, 0, 2] [2, 0, 1, 0]]
91854/531440 : [[0, 1, 1, 2] [0, 0, 2, 0] [1, 1, 1, 2]]
98415/531440 : [[1, 0, 0, 0] [1, 0, 0, 2] [1, 2, 1, 0]]
104976/531440 : [[1, 2, 2, 2] [2, 2, 2, 1] [1, 2, 2, 1]]
111537/

3×3 Matrix{Vector{Int64}}:
 [1, 1, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 0, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[0, 2, 2, 2], [2, 0, 2, 2], [1, 2, 1, 2]]


3×3 Matrix{Vector{Int64}}:
 [0, 1, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 2, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[2, 2, 0, 0], [1, 1, 2, 2], [0, 2, 1, 1]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 0, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 2, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [0, 1, 2, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[0, 0, 1, 2] [2, 0, 0, 1] [1, 1, 2, 2]]
9490 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 9490 *** Failed ***
 *** fin. ***
[[1, 1, 2, 2], [2, 0, 2, 2], [1, 0, 0, 1]]


3×3 Matrix{Vector{Int64}}:
 [2, 2, 1, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 0, 2]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6560 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 6560 *** Failed ***
 *** fin. ***
[[2, 1, 2, 0], [2, 1, 2, 2], [1, 2, 2, 2]]


3×3 Matrix{Vector{Int64}}:
 [1, 2, 1, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 2, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 1, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[1, 2, 1, 1] [2, 1, 0, 1] [0, 0, 2, 1]]
13122/531440 : [[1, 2, 0, 2] [1, 1, 0, 2] [0, 0, 1, 1]]
19683/531440 : [[2, 2, 1, 0] [1, 2, 0, 1] [2, 1, 1, 1]]
26244/531440 : [[2, 1, 2, 1] [0, 0, 0, 0] [1, 2, 0, 0]]
32805/531440 : [[1, 2, 2, 2] [1, 1, 1, 0] [2, 0, 1, 2]]
39366/531440 : [[1, 0, 2, 0] [0, 1, 0, 0] [2, 2, 0, 0]]
45927/531440 : [[1, 2, 2, 1] [2, 0, 1, 0] [2, 1, 0, 2]]
52488/531440 : [[2, 1, 2, 0] [1, 2, 2, 2] [2, 2, 1, 2]]
59049/531440 : [[0, 0, 1, 2] [0, 2, 1, 1] [0, 2, 1, 2]]
65610/531440 : [[1, 2, 1, 0] [1, 2, 0, 0] [0, 0, 1, 1]]
72171/531440 : [[2, 2, 2, 1] [1, 2, 2, 0] [1, 1, 2, 0]]
78732/531440 : [[2, 1, 0, 2] [2, 1, 0, 1] [2, 2, 2, 1]]
85293/531440 : [[0, 1, 1, 2] [1, 1, 0, 2] [1, 0, 2, 1]]
91854/531440 : [[0, 0, 1, 0] [0, 1, 1, 1] [1, 0, 0, 0]]
98415/531440 : [[2, 2, 0, 1] [1, 0, 1, 0] [0, 0, 1, 1]]
104976/531440 : [[1, 0, 2, 0] [2, 2, 1, 1] [2, 0, 1, 2]]
111537/

3×3 Matrix{Vector{Int64}}:
 [0, 0, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [2, 1, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [2, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[2, 1, 1, 2] [1, 0, 0, 0] [0, 0, 2, 2]]
13122/531440 : [[2, 0, 0, 0] [1, 1, 0, 1] [0, 2, 1, 1]]
19683/531440 : [[2, 2, 1, 0] [1, 1, 1, 1] [1, 2, 1, 0]]
26244/531440 : [[2, 0, 1, 1] [2, 2, 1, 2] [1, 1, 0, 1]]
32805/531440 : [[0, 2, 1, 1] [2, 1, 2, 0] [1, 0, 1, 2]]
39366/531440 : [[0, 1, 1, 2] [1, 1, 0, 0] [2, 0, 1, 2]]
45927/531440 : [[1, 2, 2, 1] [1, 2, 0, 1] [2, 1, 2, 1]]
52488/531440 : [[0, 1, 2, 0] [1, 1, 2, 1] [0, 0, 2, 1]]
59049/531440 : [[0, 1, 2, 1] [2, 1, 1, 2] [1, 1, 0, 0]]
65610/531440 : [[1, 2, 0, 0] [0, 2, 1, 0] [2, 2, 0, 2]]
66430 : [[0, 0, 0, 0] [0, 0, 0, 0] [0, 0, 0, 1]] 531440
*** 66430 *** Failed ***
 *** fin. ***
[[2, 2, 2, 1], [2, 0, 1, 0], [2, 2, 2, 0]]


3×3 Matrix{Vector{Int64}}:
 [1, 1, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 0, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 1, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
0/531440 : [[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
6561/531440 : [[1, 0, 2, 0] [2, 2, 2, 1] [0, 2, 2, 2]]
13122/531440 : [[1, 1, 1, 2] [1, 2, 0, 2] [1, 1, 1, 0]]
19683/531440 : [[2, 2, 1, 2] [2, 2, 1, 2] [2, 2, 0, 2]]
26244/531440 : [[0, 0, 1, 1] [0, 0, 2, 0] [0, 0, 2, 2]]
32805/531440 : [[1, 1, 1, 1] [1, 0, 0, 2] [1, 2, 2, 0]]
39366/531440 : [[2, 0, 1, 2] [0, 0, 0, 1] [2, 0, 2, 1]]
45927/531440 : [[2, 1, 1, 2] [0, 1, 1, 1] [0, 2, 2, 2]]
52488/531440 : [[1, 2, 0, 1] [1, 1, 2, 1] [1, 2, 1, 2]]
59049/531440 : [[2, 0, 2, 0] [1, 0, 1, 2] [1, 2, 1, 1]]
65610/531440 : [[1, 1, 1, 2] [1, 2, 2, 2] [0, 2, 2, 2]]
72171/531440 : [[1, 2, 0, 0] [1, 1, 1, 2] [1, 0, 0, 1]]
78732/531440 : [[2, 0, 0, 2] [2, 0, 0, 2] [1, 0, 1, 2]]
85293/531440 : [[0, 0, 0, 0] [2, 0, 1, 0] [2, 0, 0, 2]]
91854/531440 : [[0, 0, 1, 1] [0, 0, 1, 2] [2, 0, 0, 2]]
98415/531440 : [[1, 0, 2, 2] [1, 2, 1, 2] [1, 1, 0, 2]]
104976/531440 : [[0, 1, 2, 2] [1, 1, 1, 1] [0, 2, 1, 1]]
111537/

3×3 Matrix{Vector{Int64}}:
 [1, 1, 1, 2]  [0, 0, 0, 1]  [0, 0, 0, 0]
 [1, 0, 2, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]
 [1, 1, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]

> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]
1[[0, 0, 0, 0] [0, 0, 0, 1] [0, 0, 0, 0]]
2[[0, 0, 0, 1] [0, 0, 0, 0] [0, 0, 0, 0]]
77[[1, 2, 2, 0] [1, 0, 1, 2] [0, 0, 0, 0]]
103[[2, 0, 2, 0] [0, 1, 1, 0] [0, 0, 0, 0]]
278[[2, 1, 1, 2] [0, 1, 2, 0] [0, 0, 0, 0]]
306[[2, 1, 0, 2] [2, 0, 0, 0] [0, 0, 0, 0]]
309[[1, 2, 2, 2] [2, 1, 0, 1] [0, 0, 0, 0]]
350[[1, 0, 2, 1] [0, 2, 1, 2] [0, 0, 0, 0]]
534[[1, 2, 0, 2] [2, 0, 1, 0] [0, 0, 0, 0]]
612[[1, 2, 1, 2] [0, 0, 1, 1] [0, 0, 0, 0]]
733[[1, 1, 1, 0] [0, 2, 2, 0] [0, 0, 0, 0]]
901[[0, 2, 0, 2] [2, 2, 0, 0] [0, 0, 0, 0]]
1030[[1, 0, 2, 2] [1, 2, 2, 2] [0, 0, 0, 0]]
1137[[0, 2, 0, 1] [0, 2, 2, 1] [0, 0, 0, 0]]
1166[[0, 1, 2, 1] [0, 2, 2, 1] [0, 0, 0, 0]]
1216[[2, 0, 2, 2] [2, 2, 1, 1] [0, 0, 0, 0]]
1221[[2, 2, 2, 0] [1, 2, 1, 0] [0, 0, 0, 0]]
1230[[1, 1, 1, 1] [0, 0, 0, 2] [0, 0, 0, 0]]
1304[[0, 0, 1, 2] [0, 2, 0, 1] [0, 0, 0, 0]]
1353[[1, 1, 0, 1] [2, 1, 0, 2] [0, 0, 0, 0]]
1423[[0, 2, 0, 0] [0, 1, 0, 0] [0, 0, 0, 0]]
1456[[0, 2, 2, 1] [2, 0, 1,

In [111]:
(p^n)^2+1

6562

In [112]:
cdls=[cdl;cdl]
bbl=[]
for i=1:length(cdl)-2
    push!(bbl,cdls[i+1]-cdls[i])
end
bbl=bbl[1:(p^n)+1]
println(bbl)
bbls=[bbl;bbl]
chkl=[]
for i=1:p^n+1
    for j=0:p^n
        push!(chkl,sum(bbls[i:i+j]))
    end
end
println(join(sort!(unique!(chkl)),",")," : length = ",length(sort!(unique!(chkl))))
println("Total = ",(p^n)^2+p^n+1)

Any[1, 75, 26, 175, 28, 3, 41, 184, 78, 121, 168, 129, 107, 29, 50, 5, 9, 74, 49, 70, 33, 181, 57, 89, 122, 209, 25, 67, 24, 272, 46, 111, 19, 140, 188, 164, 2, 4, 12, 36, 108, 61, 10, 153, 100, 35, 23, 40, 47, 38, 30, 65, 17, 15, 7, 20, 222, 113, 34, 210, 56, 43, 62, 69, 11, 109, 141, 8, 106, 37, 53, 118, 77, 51, 45, 21, 60, 13, 280, 86, 287, 339]
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,1